### ISSUE TITLE
Site broken on Safari

### ISSUE THREAD

**Issue by mundizzle** [aidenybai/million-react#2]
<img width="772" alt="CleanShot 2022-06-14 at 17 28 22@2x" src="https://user-images.githubusercontent.com/1226055/173711368-7e674ee6-c5cf-48ab-8374-f8bf96c2770f.png">

<img width="396" alt="CleanShot 2022-06-14 at 17 29 03@2x" src="https://user-images.githubusercontent.com/1226055/173711396-11985471-b5e9-4d40-8f58-6b491239b22f.png">

![CleanShot 2022-06-14 at 17 29 18@2x](https://user-images.githubusercontent.com/1226055/173711612-9b94c2fa-5b2a-46a6-863e-98b7bbb356bc.png)

**Comment by aidenybai** [comment]
Fixed in 8451125cc0dff4341bee1d0089fbd3b905802028
