### ISSUE TITLE
Unexpected reserved word

### ISSUE THREAD

**Issue by ymatuhin** [aidenybai/million-react#4]
I'v tried to use this `const files = import.meta.glob('./posts/blog/*');` and got the error below.

<img width="898" alt="Screenshot 2022-06-17 at 21 33 25" src="https://user-images.githubusercontent.com/3757971/174357493-0547844e-0126-40d4-8e6f-bfaeea4833fd.png">

**Comment by aidenybai** [comment]
Hi @ymatuhin, could you send the source code / github repo if possible? I'm unable to determine an error with this information

**Comment by ymatuhin** [comment]
https://github.com/ymatuhin/million-error

**Comment by aidenybai** [comment]
Should be fixed on the main branch, you can update it locally by resyncing and installing, or just run `npm i million@next`
