### ISSUE TITLE
Catch boundary support?

### ISSUE THREAD

**Issue by kentcdodds** [aidenybai/million-react#6]
I noticed the limitations section and I'm mostly fine with it, but I want to make sure that catch boundaries are supported. In react those have to be class components which have limited support. Do you know whether catch boundaries will work with million?

**Comment by aidenybai** [comment]
Hey Kent, functional components don't have boundaries at the moment. This is a good feature suggestion, thanks for the feedback!

**Comment by aidenybai** [comment]
@kentcdodds @QuiiBz just shipped this in v1.12.3!

**Comment by kentcdodds** [comment]
🥳
